# opentofu/main.tf
# OpenTofu Infrastructure Definition for CMSForNerd2 Static Web Node

terraform {
  required_version = ">= 1.6.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
  }
}

provider "local" {}

# Resource representing the Nginx web root directory structure
resource "local_file" "nginx_vhost_config" {
  filename = "${path.module}/build/nginx_vhost_${var.environment}.conf"
  content  = <<-EOT
    # Auto-generated by OpenTofu IaC for CMSForNerd2 (${var.environment})
    server {
        listen ${var.server_port};
        server_name ${var.domain_name};
        root ${var.web_root};

        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # Pagefind Wasm security headers
        location /pagefind/ {
            add_header Cross-Origin-Opener-Policy "same-origin";
            add_header Cross-Origin-Embedder-Policy "require-corp";
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
  EOT
}

resource "local_file" "environment_manifest" {
  filename = "${path.module}/build/env_manifest.json"
  content = jsonencode({
    environment  = var.environment
    domain_name  = var.domain_name
    server_port  = var.server_port
    web_root     = var.web_root
    provisioned  = true
    orchestrator = "Ansible + OpenTofu"
  })
}
